[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xavis-package"
version = "0.1.0"
description = "Radio Astronomy Lab helper package"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["xavis_package"]
